name: CICD for My Application

on:
  workflow_dispatch:

jobs:
  say-welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Print Welcome World
      run: echo "Welcome, World!"

  say-bye:
    runs-on: ubuntu-latest

    steps:
    - name: Print Bye World
      run: echo "Bye , World!"
