name: CICD for My Application

on:
  workflow_dispatch:

jobs:
  say-welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Print Welcome Fouzi
      run: echo "Welcome, Fouzi!"

  say-bye:
    runs-on: ubuntu-latest

    steps:
    - name: Print Bye Fouzi
      run: echo "Bye , Fouzi!"
